export const RegionsAndCities = [
  'Arcos',
  'Alterosa',
  'Barbacena',
  'Belo Horizonte',
  'Betim',
  'Boa Esperança',
  'Bom Despacho',
  'Brumadinho',
  'Caeté',
  'Campos Gerais',
  'Coronel Fabriciano',
  'Carandai',
  'Confins',
  'Congonhas',
  'Contagem',
  'Conselheiro Lafaiete',
  'Curvelo',
  'Divinópolis',
  'Elói Mendes',
  'Florestal',
  'Formiga',
  'Guapé',
  'Guarani',
  'Ibirite',
  'Itabirito',
  'Itapecerica',
  'Itaúna',
  'Itaú de Minas',
  'Juiz de Fora',
  'Juruaia',
  'Lagoa Santa',
  'Matozinhos',
  'Nova Lima',
  'Nova Resende',
  'Oliveira',
  'Ouro Branco',
  'Pará de Minas',
  'Paraguaçu',
  'Passos',
  'Patrocínio',
  'Pedro Leopoldo',
  'Piraúba',
  'Prudente de Morais',
  'Ribeirão das Neves',
  'Santa Luzia',
  'Santana do Paraiso',
  'São Lourenço',
  'São João Del Rey',
  'São José da Barra',
  'São José da Lapa',
  'São Sebastião do Paraiso',
  'Sete Lagoas',
  'Tocantins',
  'Ubá',
  'Vespasiano',
]